### ISSUE TITLE
Retire the embedded .deb file

### ISSUE THREAD

**Issue by threepistons** [newcastleuniversity/puppet_module_microsoft_teams_installer#1]
# Todo list:

- [x] Extract the details of the MS repo and its signing key from a Debian-like system that already has the Teams client installed.
- [x] Add the [puppetlabs/apt](https://forge.puppet.com/modules/puppetlabs/apt) module and its dependencies to the metadata.json and .fixtures.yaml files, using the versions in use in the control repo's Puppetfile.
- [x] Write unit tests for the Apt and Apt::key and Package resources that I think I need...
- [x] ...and the matching resource files.
- [x] Acceptance test against my PC by adding the module to the control repo's Puppetfile and the module to my PC's node definition.

# Why?

1. Current implementation requires replacement of the deb file to update the version of Teams installed by this module.
2. Deb files in the repo make the repo huge.
3. I found out the hard way that [Puppet control repos and Git LFS don't work together][1] (full text below) so using LFS isn't an option to keep the repo size down.  Even if LFS worked, it would still leave point 1 unaddressed.

> ```
> cs-puppet5:/etc/puppetlabs/code/environments/master/modules/> file teams/files/teams_1.2.00.32451_amd64.deb`
> teams/files/teams_1.2.00.32451_amd64.deb: ASCII text
> ```
> The content is a short text file, not a .deb file.  And yes, the short text file is what ends up on the agents. :angry:  De-LFSing a repo turned out to be beyond me (git lfs uninstall and untracking the file didn't work) so I had to delete the .git folder and reinitialise the git repo.

 
[1]: https://teams.microsoft.com/l/message/19:2910b867b0cb4eb99778bd23c71de444@thread.skype/1576524320998?tenantId=9c5012c9-b616-44c2-a917-66814fbe3e87&groupId=8f1a3a96-af2a-4a1b-a0a7-e433147020fc&parentMessageId=1576524320998&teamName=NUIT-LINUX_Virtual_Group&channelName=General&createdTime=1576524320998
